version: '3.7'

services:
  web:
    image: ruby:3.4.2
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    container_name: my_store_web
    working_dir: /my_store
    volumes:
      - ".:/my_store"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_store_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - my_store_db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  my_store_db_data:

